[package]
name = "simple-deep-learning"
version = "0.1.0"
edition = "2024"

[dependencies]
tch = "0.19.0" # Or try the latest stable version available
reqwest = { version = "0.11", features = ["blocking"] }
flate2 = "1.0"
